language: node_js
node_js:
  - "5.1"

before_install:
  npm install typescript

script:
  - npm test
  - npm i sidekick
  - sidekick -v
  - sidekick run --ci

notifications:
  slack: we-are-sidekick:GeIT5wtuKMLImpFXYHWzIGzI
